# generated by datamodel-codegen:
#   filename:  agent_event.schema.json
#   timestamp: 2026-03-03T01:18:26+00:00

from __future__ import annotations

from typing import Annotated, Any

from pydantic import BaseModel, ConfigDict, Field


class AgentEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Annotated[
        str,
        Field(
            description='Event type (e.g., agent.tool.progress, agent.placeholders, delta, done, error)'
        ),
    ]
    data: dict[str, Any] | None = None
    sequence: int | None = None
