# generated by datamodel-codegen:
#   filename:  chat_request.schema.json
#   timestamp: 2026-02-10T05:23:09+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict

from . import chat_event_schema, placeholder_map_schema, tool_settings_schema


class ChatRequest(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    messages: list[chat_event_schema.ChatEvent]
    recursion_limit: int | None = None
    placeholderMap: placeholder_map_schema.PlaceholderMap | None = None
    toolSettings: tool_settings_schema.ToolSettings | None = None
    tool_choice: dict[str, Any] | str | None = None
    llm: str | None = None
    timeZone: str | None = None
