# generated by datamodel-codegen:
#   filename:  chat_event.schema.json
#   timestamp: 2026-03-03T01:18:26+00:00

from __future__ import annotations

from enum import Enum
from typing import Any

from pydantic import BaseModel, ConfigDict


class Role(Enum):
    system = 'system'
    user = 'user'
    assistant = 'assistant'
    tool = 'tool'


class ChatEvent(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str | int | None = None
    role: Role
    user: str | None = None
    content: str
    tool_calls: list[dict[str, Any]] | None = None
    tool_call_id: str | None = None
    name: str | None = None
    timestamp: int | None = None
    files: list[dict[str, Any]] | None = None
