# generated by datamodel-codegen:
#   filename:  placeholder_map.schema.json
#   timestamp: 2026-03-03T01:18:26+00:00

from __future__ import annotations

from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel


class PlaceholderMapItem(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    placeholder: str
    original: str


class PlaceholderMap(RootModel[dict[str, str] | list[PlaceholderMapItem]]):
    root: Annotated[
        dict[str, str] | list[PlaceholderMapItem],
        Field(
            description='Mapping between placeholders and originals. Supports object-map or array-of-entries forms.',
            title='PlaceholderMap',
        ),
    ]
