# generated by datamodel-codegen:
#   filename:  tool_settings.schema.json
#   timestamp: 2026-03-03T01:18:26+00:00

from __future__ import annotations

from pydantic import BaseModel, ConfigDict


class ToolSettings(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    biFunctionsEnabled: bool | None = None
    webSearchEnabled: bool | None = None
    imageGenEnabled: bool | None = None
