# generated by datamodel-codegen:
#   filename:  tool_definition.schema.json
#   timestamp: 2026-02-10T05:23:09+00:00

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class ToolDefinition(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: str
    description: str | None = None
    parameters: dict[str, Any] | None = None
    source: Annotated[
        str | None,
        Field(description='Tool origin (e.g., mcp, builtin, internal, external).'),
    ] = None
    tool_type: Annotated[
        Literal['non_agentic', 'agentic'] | None,
        Field(
            description='Tool execution mode. non_agentic resolves placeholders before call; agentic receives placeholders and manages nested tool resolution itself.'
        ),
    ] = None
