# generated by datamodel-codegen:
#   filename:  tool_call.schema.json
#   timestamp: 2026-02-10T05:23:09+00:00

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, ConfigDict


class ToolCall(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: str
    name: str
    arguments: dict[str, Any]
